function K = K(E,I,L)
%K
%    K = K(E,I,L)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    14-Dec-2022 16:56:56

t2 = 1.0./L;
t3 = (E.*I)./1.0e+1;
t4 = E.*I.*L.*(2.0./1.5e+1);
t5 = (E.*I.*L)./3.0e+1;
t6 = -t3;
t7 = -t5;
t8 = E.*I.*t2.*(6.0./5.0);
t9 = -t8;
K = reshape([t8,t3,t9,t3,t3,t4,t6,t7,t9,t6,t8,t6,t3,t7,t6,t4],[4,4]);
