function M = M(rho,A,L)
%M
%    M = M(RHO,A,L)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    14-Dec-2022 12:52:53

t2 = L.^2;
t3 = L.^3;
t4 = A.*L.*rho.*(1.3e+1./3.5e+1);
t5 = A.*L.*rho.*(9.0./7.0e+1);
t6 = (A.*rho.*t3)./1.05e+2;
t7 = (A.*rho.*t3)./1.4e+2;
t9 = A.*rho.*t2.*(1.1e+1./2.1e+2);
t10 = A.*rho.*t2.*(1.3e+1./4.2e+2);
t8 = -t7;
t11 = -t9;
t12 = -t10;
M = reshape([t4,t9,t5,t12,t9,t6,t10,t8,t5,t10,t4,t11,t12,t8,t11,t6],[4,4]);
